<?php

declare(strict_types = 1);

namespace Tests\Functional;

use PHPUnit\Framework\TestCase;
use Popo\Builder\BuilderConfigurator;
use Popo\PopoFacade;
use Popo\PopoFactory;
use Popo\Schema\Reader\SchemaInterface;
use function trim;
use const Popo\APPLICATION_DIR;
use const Popo\TESTS_DIR;

class PopoFacadeStringTest extends TestCase
{
    /**
     * @var string
     */
    protected $schemaDirectory;

    /**
     * @var string
     */
    protected $templateDirectory;

    /**
     * @var \Popo\PopoFactoryInterface
     */
    protected $popoFactory;

    /**
     * @var string
     */
    protected $outputDirectory;

    protected function setUp(): void
    {
        $this->popoFactory = new PopoFactory();

        $this->schemaDirectory = TESTS_DIR . 'fixtures/';
        $this->templateDirectory = APPLICATION_DIR . 'templates/';
        $this->outputDirectory = TESTS_DIR . 'App/Generated/';
    }

    protected function buildSchema(array $schemaData): SchemaInterface
    {
        $schema = $this->popoFactory
            ->createReaderFactory()->createSchema($schemaData);

        return $schema;
    }

    public function testGeneratePopoString(): void
    {
        $facade = new PopoFacade();

        $configurator = (new BuilderConfigurator())
            ->setTemplateDirectory($this->templateDirectory)
            ->setNamespace('Popo\Tests');

        $schemaData = [
            'name' => 'FooGenerated',
            'schema' => [[
                'name' => 'fooId',
                'type' => 'int',
            ]],
        ];

        $schema = $this->buildSchema($schemaData);
        $generatedString = $facade->generatePopoString($configurator, $schema);

        $expectedString = '
<?php

declare(strict_types = 1);

namespace Popo\Tests;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
class FooGenerated 
{
    /**
     * @var array
     */
    protected $data = array (
);

    /**
     * @var array
     */
    protected $default = array (
);

    /**
     * @var array
     */
    protected $propertyMapping = array (
  \'fooId\' => \'int\',
);

    /**
     * @var array
     */
    protected $collectionItems = array (
  \'fooId\' => \'\',
);

    /**
     * @var array
     */
    protected $updateMap = [];

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            $className = trim($this->propertyMapping[$property]);
            if ($className !== \'\'  && class_exists($className)) {
                $this->data[$property] = new $className();
            } else {
                return null;
            }
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;

        $this->updateMap[$property] = true;
    }

    /**
     * @return array
     */
    protected function getPropertyNames(): array
    {
        return \array_keys(
            $this->propertyMapping
        );
    }

    protected function isCollectionItem(string $key, array $data): bool
    {
        return $this->collectionItems[$key] !== \'\' &&
            \is_array($data[$key]) &&
            \class_exists($this->collectionItems[$key]);
    }

    /**
     * @param string $property
     *
     * @throws \UnexpectedValueException
     * @return void
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new \UnexpectedValueException(\sprintf(
                \'Required value of "%s" has not been set\',
                $property
            ));
        }
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @throws \InvalidArgumentException
     * @return void
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = \trim(\strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!\is_array($collection) || $type !== \'array\') {
            throw new \InvalidArgumentException(\'Cannot add item to non array type: \' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    
    public function toArray(): array
    {
        $data = $this->prepareToArrayData();

        foreach ($this->propertyMapping as $key => $type) {
            $data[$key] = $this->default[$key] ?? null;

            if (isset($this->data[$key])) {
                $value = $this->data[$key];

                if ($this->collectionItems[$key] !== \'\') {
                    if (\is_array($value) && \class_exists($this->collectionItems[$key])) {
                        foreach ($value as $popo) {
                            if (\method_exists($popo, \'toArray\')) {
                                $data[$key][] = $popo->toArray();
                            }
                        }
                    }
                } else {
                    $data[$key] = $value;
                }

                if (\is_object($value) && \method_exists($value, \'toArray\')) {
                    $data[$key] = $value->toArray();
                }
            }
        }

        return $data;
    }

    public function fromArray(array $data): <<RETURN_TYPE>>
    {
        $result = $this->prepareFromArrayData($data);

        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = null;
            if (\array_key_exists($key, $this->default)) {
                $result[$key] = $this->default[$key];
            }
            if (\array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key, $data)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (\method_exists($popo, \'fromArray\')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                } else {
                    $result[$key] = $data[$key];
                }
            }

            if (\class_exists($type)) {
                $popo = new $type();
                if (\is_array($result[$key]) && \method_exists($popo, \'fromArray\')) {
                    $popo->fromArray($result[$key]);
                }
                $result[$key] = $popo;
            }
        }

        $this->data = $result;

        foreach ($data as $key => $value) {
            if (!\array_key_exists($key, $result)) {
                continue;
            }

            $type = $this->propertyMapping[$key] ?? \'string\';
            $value = $this->typecastValue($type, $result[$key]);
            $this->popoSetValue($key, $value);
        }

        return $this;
    }

    protected function prepareToArrayData(): array
    {
        $data = [];
        $parents = \class_parents($this, false);
        if (count($parents) === 1 && \current($parents) === \get_class($this)) {
            $data = [];
        } else if (count($parents) > 1) {
            $parent = \get_parent_class($this);
            if (method_exists($parent, \'toArray\')) {
                $data = parent::toArray();
            }
        }
        return $data;
    }

    protected function prepareFromArrayData(array $data): array
    {
        $result = [];
        $parents = \class_parents($this, false);

        if (count($parents) === 1 && \current($parents) === \get_class($this)) {
            $result = $data;
        } else if (count($parents) > 1) {
            $parent = \get_parent_class($this);
            if (method_exists($parent, \'fromArray\')) {
                $result = parent::fromArray($data);
            }
        }
        return $result;
    }

    protected function typecastValue(string $type, $value)
    {
        if ($value === null) {
            return $value;
        }

        switch ($type) {
            case \'int\':
                $value = (int)$value;
                break;
            case \'string\':
                $value = (string)$value;
                break;
            case \'bool\':
                $value = (bool)$value;
                break;
            case \'array\':
                $value = (array)$value;
                break;
        }

        return $value;
    }


    
    /**
     * @return integer|null
     */
    public function getFooId(): ?int
    {
        return $this->popoGetValue(\'fooId\');
    }

    /**
     * @param integer|null $fooId
     *
     * @return self
     */
    public function setFooId(?int $fooId): \Popo\Tests\FooGenerated
    {
        $this->popoSetValue(\'fooId\', $fooId);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @throws \UnexpectedValueException
     *
     * @return integer
     */
    public function requireFooId(): int
    {
        $this->assertPropertyValue(\'fooId\');

        return (int)$this->popoGetValue(\'fooId\');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasFooId(): bool
    {
        return $this->updateMap[\'fooId\'] ?? false;
    }


    
}
';

        $this->assertEquals(trim($expectedString), trim($generatedString));
    }

    public function SKIP_testGenerateDtoString(): void
    {
        $facade = new PopoFacade();

        $configurator = (new BuilderConfigurator())
            ->setTemplateDirectory($this->templateDirectory)
            ->setNamespace('Popo\Tests');

        $schemaData = [
            'name' => 'FooGenerated',
            'schema' => [[
                'name' => 'fooId',
                'type' => 'int',
            ]],
        ];

        $schema = $this->buildSchema($schemaData);
        $generatedString = $facade->generateDtoString($configurator, $schema);

        $expectedString = '
<?php

declare(strict_types = 1);

namespace Popo\Tests;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
class FooGenerated implements \Popo\Tests\FooGeneratedInterface
{
    /**
     * @var array
     */
    protected $data = array (
);

    /**
     * @var array
     */
    protected $default = array (
);

    /**
     * @var array
     */
    protected $propertyMapping = array (
  \'fooId\' => \'int\',
);

    /**
     * @var array
     */
    protected $collectionItems = array (
  \'fooId\' => \'\',
);

    /**
     * @var array
     */
    protected $updateMap = [];

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            $className = trim($this->propertyMapping[$property]);
            if ($className !== \'\'  && class_exists($className)) {
                $this->data[$property] = new $className();
            } else {
                return null;
            }
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;

        $this->updateMap[$property] = true;
    }

    /**
     * @return array
     */
    protected function getPropertyNames(): array
    {
        return \array_keys(
            $this->propertyMapping
        );
    }

    protected function isCollectionItem(string $key, array $data): bool
    {
        return $this->collectionItems[$key] !== \'\' &&
            \is_array($data[$key]) &&
            \class_exists($this->collectionItems[$key]);
    }

    /**
     * @param string $property
     *
     * @throws \UnexpectedValueException
     * @return void
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new \UnexpectedValueException(\sprintf(
                \'Required value of "%s" has not been set\',
                $property
            ));
        }
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @throws \InvalidArgumentException
     * @return void
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = \trim(\strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!\is_array($collection) || $type !== \'array\') {
            throw new \InvalidArgumentException(\'Cannot add item to non array type: \' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    
    public function toArray(): array
    {
        $data = $this->prepareToArrayData();

        foreach ($this->propertyMapping as $key => $type) {
            $data[$key] = $this->default[$key] ?? null;

            if (isset($this->data[$key])) {
                $value = $this->data[$key];

                if ($this->collectionItems[$key] !== \'\') {
                    if (\is_array($value) && \class_exists($this->collectionItems[$key])) {
                        foreach ($value as $popo) {
                            if (\method_exists($popo, \'toArray\')) {
                                $data[$key][] = $popo->toArray();
                            }
                        }
                    }
                } else {
                    $data[$key] = $value;
                }

                if (\is_object($value) && \method_exists($value, \'toArray\')) {
                    $data[$key] = $value->toArray();
                }
            }
        }

        return $data;
    }

    public function fromArray(array $data): <<RETURN_TYPE>>
    {
        $result = $this->prepareFromArrayData($data);

        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = null;
            if (\array_key_exists($key, $this->default)) {
                $result[$key] = $this->default[$key];
            }
            if (\array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key, $data)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (\method_exists($popo, \'fromArray\')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                } else {
                    $result[$key] = $data[$key];
                }
            }

            if (\class_exists($type)) {
                $popo = new $type();
                if (\is_array($result[$key]) && \method_exists($popo, \'fromArray\')) {
                    $popo->fromArray($result[$key]);
                }
                $result[$key] = $popo;
            }
        }

        $this->data = $result;

        foreach ($data as $key => $value) {
            if (!\array_key_exists($key, $result)) {
                continue;
            }

            $type = $this->propertyMapping[$key] ?? \'string\';
            $value = $this->typecastValue($type, $result[$key]);
            $this->popoSetValue($key, $value);
        }

        return $this;
    }

    protected function prepareToArrayData(): array
    {
        $data = [];
        $parents = \class_parents($this, false);
        if (count($parents) === 1 && \current($parents) === \get_class($this)) {
            $data = [];
        } else if (count($parents) > 1) {
            $parent = \get_parent_class($this);
            if (method_exists($parent, \'toArray\')) {
                $data = parent::toArray();
            }
        }
        return $data;
    }

    protected function prepareFromArrayData(array $data): array
    {
        $result = [];
        $parents = \class_parents($this, false);

        if (count($parents) === 1 && \current($parents) === \get_class($this)) {
            $result = $data;
        } else if (count($parents) > 1) {
            $parent = \get_parent_class($this);
            if (method_exists($parent, \'fromArray\')) {
                $result = parent::fromArray($data);
            }
        }
        return $result;
    }

    protected function typecastValue(string $type, $value)
    {
        if ($value === null) {
            return $value;
        }

        switch ($type) {
            case \'int\':
                $value = (int)$value;
                break;
            case \'string\':
                $value = (string)$value;
                break;
            case \'bool\':
                $value = (bool)$value;
                break;
            case \'array\':
                $value = (array)$value;
                break;
        }

        return $value;
    }


    
    /**
     * @return integer|null
     */
    public function getFooId(): ?int
    {
        return $this->popoGetValue(\'fooId\');
    }

    /**
     * @param integer|null $fooId
     *
     * @return self
     */
    public function setFooId(?int $fooId): \Popo\Tests\FooGeneratedInterface
    {
        $this->popoSetValue(\'fooId\', $fooId);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @throws \UnexpectedValueException
     *
     * @return integer
     */
    public function requireFooId(): int
    {
        $this->assertPropertyValue(\'fooId\');

        return (int)$this->popoGetValue(\'fooId\');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasFooId(): bool
    {
        return $this->updateMap[\'fooId\'] ?? false;
    }


    
}
';

        $this->assertEquals(trim($expectedString), trim($generatedString));
    }

    public function SKIP_testGenerateDtoInterfaceString(): void
    {
        $facade = new PopoFacade();

        $configurator = (new BuilderConfigurator())
            ->setTemplateDirectory($this->templateDirectory)
            ->setNamespace('Popo\Tests');

        $schemaData = [
            'name' => 'FooGenerated',
            'schema' => [[
                'name' => 'fooId',
                'type' => 'int',
            ]],
        ];

        $schema = $this->buildSchema($schemaData);
        $generatedString = $facade->generateDtoInterfaceString($configurator, $schema);

        $expectedString = '
<?php

declare(strict_types = 1);

namespace Popo\Tests;

interface FooGeneratedInterface
{
    /**
    * @return array
    */
    public function toArray(): array;

    /**
    * @param array $data
    *
    * @return \Popo\Tests\FooGeneratedInterface
    */
    public function fromArray(array $data): \Popo\Tests\FooGeneratedInterface;

    
    /**
     * @return integer|null
     */
    public function getFooId(): ?int;

    /**
     * @param integer|null $fooId
     *
     * @return self
     */
    public function setFooId(?int $fooId): \Popo\Tests\FooGeneratedInterface;

    /**
     * Throws exception if value is null.
     *
     * @throws \UnexpectedValueException
     *
     * @return integer
     */
    public function requireFooId(): int;

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasFooId(): bool;


    
}
';

        $this->assertEquals(trim($expectedString), trim($generatedString));
    }
}
