<?php

declare(strict_types = 1);

namespace <<NAMESPACE>>;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
<<ABSTRACT>>class <<CLASSNAME>><<EXTENDS>> <<IMPLEMENTS_INTERFACE>>
{
    abstract public function toArray(): array;

    abstract public function fromArray(array $data): <<RETURN_TYPE>>;
}
