name: Build and run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: docker-compose run cli composer install
      - name: Run the tests
        run: docker-compose run cli composer tests
